name: Build Masscan (MSYS2 / MinGW64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-libpcap
            mingw-w64-x86_64-pkg-config
            make
            git

      - name: Verify environment
        run: |
          echo "=== MSYS2 Build Environment ==="
          echo "MSYSTEM=$MSYSTEM"
          uname -a
          which gcc
          gcc --version
          echo "libpcap:"
          pacman -Qi mingw-w64-x86_64-libpcap || true

      - name: Build Masscan (MINGW64)
        run: |
          echo "=== Building Masscan ==="
          export PATH="/mingw64/bin:$PATH"
          git submodule update --init --recursive || true

          # Clean and rebuild
          make clean || true
          make -j$(nproc) CC=gcc || make CC=gcc

          echo "=== Build output ==="
          find . -type f -iname "masscan.exe" || true
          ls -lah bin || true

      - name: Upload compiled executables
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: masscan-windows-mingw64
          path: |
            **/masscan.exe
            bin/*.exe
            dist/*.exe
